#ifndef MASTERKLONDIKE_MODELS_DECK_DECKTYPE_H_
#define MASTERKLONDIKE_MODELS_DECK_DECKTYPE_H_

enum class DeckType {REMAIN, WASTE, FOUNDATION, TABLEU, COUNT};

#endif /* MASTERKLONDIKE_MODELS_DECK_DECKTYPE_H_ */
