#ifndef MASTERKLONDIKE_MODELS_FOUNDATIONTYPE_H_
#define MASTERKLONDIKE_MODELS_FOUNDATIONTYPE_H_

enum class FoundationType {DIAMONDS, CLUBS, HEARTS, SPADES, COUNT};

#endif /* MASTERKLONDIKE_MODELS_FOUNDATIONTYPE_H_ */
